/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashscreensatu;

import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class BiodataMemeber extends javax.swing.JFrame {

    /**
     * Creates new form BiodataMemeber
     */
    public BiodataMemeber() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Jeonjungkook = new javax.swing.JButton();
        Kimtaehyung = new javax.swing.JButton();
        minyoongi = new javax.swing.JButton();
        kimnamjoon = new javax.swing.JButton();
        junghoseok = new javax.swing.JButton();
        kimseokjin = new javax.swing.JButton();
        parkjimin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JeonJungkook = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        homeJK = new javax.swing.JButton();
        quitJK = new javax.swing.JButton();
        foto1 = new javax.swing.JLabel();
        background11 = new javax.swing.JLabel();
        KimTaehyung = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        homeTH = new javax.swing.JButton();
        quitTH = new javax.swing.JButton();
        foto2 = new javax.swing.JLabel();
        background12 = new javax.swing.JLabel();
        MinYoongi = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        homeSG = new javax.swing.JButton();
        quitSG = new javax.swing.JButton();
        foto3 = new javax.swing.JLabel();
        background13 = new javax.swing.JLabel();
        KimNamjoon = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        homeNM = new javax.swing.JButton();
        quitNM = new javax.swing.JButton();
        foto4 = new javax.swing.JLabel();
        background14 = new javax.swing.JLabel();
        Junghoseok = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        homeJH = new javax.swing.JButton();
        quitJH = new javax.swing.JButton();
        foto5 = new javax.swing.JLabel();
        background15 = new javax.swing.JLabel();
        KimSeokjin = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        homeSJ = new javax.swing.JButton();
        quitSJ = new javax.swing.JButton();
        foto6 = new javax.swing.JLabel();
        background16 = new javax.swing.JLabel();
        ParkJimin1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        homeSJ1 = new javax.swing.JButton();
        quitSJ1 = new javax.swing.JButton();
        foto8 = new javax.swing.JLabel();
        background18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 204, 0));

        Jeonjungkook.setForeground(new java.awt.Color(102, 0, 0));
        Jeonjungkook.setText("Jeon Jungkook");
        Jeonjungkook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JeonjungkookActionPerformed(evt);
            }
        });

        Kimtaehyung.setForeground(new java.awt.Color(102, 0, 0));
        Kimtaehyung.setText("Kim Taehyung");
        Kimtaehyung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KimtaehyungActionPerformed(evt);
            }
        });

        minyoongi.setForeground(new java.awt.Color(102, 0, 0));
        minyoongi.setText("Min Yoongi");
        minyoongi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minyoongiActionPerformed(evt);
            }
        });

        kimnamjoon.setForeground(new java.awt.Color(102, 0, 0));
        kimnamjoon.setText("Kim Namjoon");
        kimnamjoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimnamjoonActionPerformed(evt);
            }
        });

        junghoseok.setForeground(new java.awt.Color(102, 0, 0));
        junghoseok.setText("Jung Hoseok");
        junghoseok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                junghoseokActionPerformed(evt);
            }
        });

        kimseokjin.setForeground(new java.awt.Color(102, 0, 0));
        kimseokjin.setText("Kim Seokjin");
        kimseokjin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimseokjinActionPerformed(evt);
            }
        });

        parkjimin.setForeground(new java.awt.Color(102, 0, 0));
        parkjimin.setText("Park Jimin");
        parkjimin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkjiminActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biodata Member :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parkjimin)
                    .addComponent(junghoseok)
                    .addComponent(kimnamjoon)
                    .addComponent(minyoongi)
                    .addComponent(Kimtaehyung)
                    .addComponent(Jeonjungkook)
                    .addComponent(kimseokjin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jeonjungkook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kimtaehyung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minyoongi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kimnamjoon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(junghoseok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kimseokjin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parkjimin)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 900));

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 0));

        JeonJungkook.setPreferredSize(new java.awt.Dimension(1400, 900));
        JeonJungkook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Nama Panggung: Jungkook\nNama Asli: Jeon Jeong-guk\nUlang Tahun: 1 September 1997\nZodiak: Virgo\nTempat Lahir: Busan, Korea Selatan\nTinggi Badan: 178 cm (5’10”)\nBerat Badan: 66 kg (145 lbs)\nGolongan Darah: A");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        JeonJungkook.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 500, 220));

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jeon Jungkook");
        JeonJungkook.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 340, 110));

        homeJK.setText("HOME");
        homeJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJKActionPerformed(evt);
            }
        });
        JeonJungkook.add(homeJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        quitJK.setText("Keluar");
        quitJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJKActionPerformed(evt);
            }
        });
        JeonJungkook.add(quitJK, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 70, -1));

        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/jeon jungkook1.jpg"))); // NOI18N
        foto1.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 0, 0)));
        JeonJungkook.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, 480));

        background11.setForeground(new java.awt.Color(153, 0, 153));
        background11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/40 AMAZING SPACE AESTHETIC WALLPAPER FOR YOUR IPHONE!.jpg"))); // NOI18N
        JeonJungkook.add(background11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 970));

        jTabbedPane1.addTab("Jeon Jungkook", JeonJungkook);

        KimTaehyung.setPreferredSize(new java.awt.Dimension(1400, 900));
        KimTaehyung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Nama Panggung: V\nNama asli: Kim Tae Hyung (김태형)\nTanggal lahir: December 30, 1995\nZodiak: Capricorn\nTempat lahir: Daegu\nTinggi badan: 178 cm (5’10″)\nBerat badan: 62 kg (137 lbs)\nGolongan darah: AB");
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        KimTaehyung.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 500, 220));

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kim Taehyung");
        KimTaehyung.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 340, 110));

        homeTH.setText("HOME");
        homeTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeTHActionPerformed(evt);
            }
        });
        KimTaehyung.add(homeTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        quitTH.setText("Keluar");
        quitTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitTHActionPerformed(evt);
            }
        });
        KimTaehyung.add(quitTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 70, -1));

        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/kim taehyung1.jpg"))); // NOI18N
        foto2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 0, 0)));
        KimTaehyung.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, 480));

        background12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/40 AMAZING SPACE AESTHETIC WALLPAPER FOR YOUR IPHONE!.jpg"))); // NOI18N
        KimTaehyung.add(background12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -100, 1310, 1010));

        jTabbedPane1.addTab("tab2", KimTaehyung);

        MinYoongi.setPreferredSize(new java.awt.Dimension(1400, 900));
        MinYoongi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(null);
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Nama Panggung: Suga\nNama Asli: Min Yoon Gi\nUlang Tahun: 9 Maret 1993\nZodiak: Pisces\nTempat Lahir: Buk-gu, Daegu\nTinggi Badan: 174 cm (5’8.5″)\nBerat Badan: 59 kg (130 lbs)\nGolongan Darah: O");
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);

        MinYoongi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 500, 220));

        jLabel4.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Min Yoongi");
        MinYoongi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 340, 110));

        homeSG.setText("HOME");
        homeSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSGActionPerformed(evt);
            }
        });
        MinYoongi.add(homeSG, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        quitSG.setText("Keluar");
        quitSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitSGActionPerformed(evt);
            }
        });
        MinYoongi.add(quitSG, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 70, -1));

        foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/min yonggi1.jpg"))); // NOI18N
        foto3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 0, 0)));
        MinYoongi.add(foto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, 480));

        background13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/40 AMAZING SPACE AESTHETIC WALLPAPER FOR YOUR IPHONE!.jpg"))); // NOI18N
        MinYoongi.add(background13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 1010));

        jTabbedPane1.addTab("tab3", MinYoongi);

        KimNamjoon.setPreferredSize(new java.awt.Dimension(1400, 900));
        KimNamjoon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(null);
        jScrollPane4.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Nama Panggung: RM \nNama Lengkap: Kim Namjoon\nUlang Tahun: 12 September 1994\nZodiak: Virgo\nTempat Lahir: Ilsan, Gyeonggi\nTinggi Badan: 181.68 cm (5’11”)\nBerat Badan: 67 kg (147 lbs)\nGolongan Darah: A");
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);

        KimNamjoon.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 500, 220));

        jLabel5.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kim Namjoon");
        KimNamjoon.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 340, 110));

        homeNM.setText("HOME");
        homeNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeNMActionPerformed(evt);
            }
        });
        KimNamjoon.add(homeNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        quitNM.setText("Keluar");
        quitNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitNMActionPerformed(evt);
            }
        });
        KimNamjoon.add(quitNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 70, -1));

        foto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/kim namjoon1.jpg"))); // NOI18N
        foto4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 0, 0)));
        KimNamjoon.add(foto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, 480));

        background14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/40 AMAZING SPACE AESTHETIC WALLPAPER FOR YOUR IPHONE!.jpg"))); // NOI18N
        KimNamjoon.add(background14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -100, 1310, 1010));

        jTabbedPane1.addTab("tab4", KimNamjoon);

        Junghoseok.setPreferredSize(new java.awt.Dimension(1400, 900));
        Junghoseok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setBorder(null);
        jScrollPane5.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Nama Panggung: J-Hope\nNama Asli: Jung Ho Seok\nUlang Tahun: February 18, 1994\nZodiak: Aquarius\nTempat Lahir: Gwangju\nTinggi Badan: 177 cm (5’10”)\nBerat Badan: 65 kg (143 lbs)\nGolongan Darah: A");
        jTextArea5.setBorder(null);
        jScrollPane5.setViewportView(jTextArea5);

        Junghoseok.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 500, 220));

        jLabel6.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jung Hoseok");
        Junghoseok.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 340, 110));

        homeJH.setText("HOME");
        homeJH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJHActionPerformed(evt);
            }
        });
        Junghoseok.add(homeJH, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        quitJH.setText("Keluar");
        quitJH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJHActionPerformed(evt);
            }
        });
        Junghoseok.add(quitJH, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 70, -1));

        foto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/jung hoseok1.jpg"))); // NOI18N
        foto5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 0, 0)));
        Junghoseok.add(foto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, 480));

        background15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/40 AMAZING SPACE AESTHETIC WALLPAPER FOR YOUR IPHONE!.jpg"))); // NOI18N
        Junghoseok.add(background15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -100, 1310, 1010));

        jTabbedPane1.addTab("tab5", Junghoseok);

        KimSeokjin.setPreferredSize(new java.awt.Dimension(1400, 900));
        KimSeokjin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane6.setBorder(null);
        jScrollPane6.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setText("Nama Panggung: Jin\nNama Asli: Kim Seok Jin (김석진)\nUlang Tahun: 4 Desember 1992\nZodiak: Sagittarius\nTempat Lahir: Anyang, Gyeonggi.\nTinggi Badan: 179 cm (5’10.5”)\nBerat Badan: 63 kg (139 lbs)\nGolongan Darah: O");
        jTextArea6.setBorder(null);
        jScrollPane6.setViewportView(jTextArea6);

        KimSeokjin.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 500, 220));

        jLabel7.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kim Seokjin");
        KimSeokjin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 340, 110));

        homeSJ.setText("HOME");
        homeSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSJActionPerformed(evt);
            }
        });
        KimSeokjin.add(homeSJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        quitSJ.setText("Keluar");
        quitSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitSJActionPerformed(evt);
            }
        });
        KimSeokjin.add(quitSJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 70, -1));

        foto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/kim seokjin1.jpg"))); // NOI18N
        foto6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 0, 0)));
        KimSeokjin.add(foto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 270, 480));

        background16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/40 AMAZING SPACE AESTHETIC WALLPAPER FOR YOUR IPHONE!.jpg"))); // NOI18N
        KimSeokjin.add(background16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -160, 1310, 1010));

        jTabbedPane1.addTab("tab6", KimSeokjin);

        ParkJimin1.setPreferredSize(new java.awt.Dimension(1400, 900));
        ParkJimin1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane8.setBorder(null);
        jScrollPane8.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 204))); // NOI18N

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(102, 0, 0));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setText("Nama Panggung: Jimin\nNama Asli: Park Ji Min\nUlang Tahun: October 13, 1995\nZodiak: Libra\nTempat Lahir: Busan\nTinggi Badan: 173.6cm (5’8.3″)\nBerat Badan: 61 kg (134 lbs)\nGolongan Darah: A");
        jTextArea8.setBorder(null);
        jScrollPane8.setViewportView(jTextArea8);

        ParkJimin1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 500, 220));

        jLabel9.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Park Jimin");
        ParkJimin1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 340, 110));

        homeSJ1.setText("HOME");
        homeSJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSJ1ActionPerformed(evt);
            }
        });
        ParkJimin1.add(homeSJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        quitSJ1.setText("Keluar");
        quitSJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitSJ1ActionPerformed(evt);
            }
        });
        ParkJimin1.add(quitSJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 70, -1));

        foto8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/park jimin1.jpg"))); // NOI18N
        foto8.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(102, 0, 0)));
        ParkJimin1.add(foto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, 480));

        background18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/40 AMAZING SPACE AESTHETIC WALLPAPER FOR YOUR IPHONE!.jpg"))); // NOI18N
        ParkJimin1.add(background18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1310, 1010));

        jTabbedPane1.addTab("tab7", ParkJimin1);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -30, 1220, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parkjiminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkjiminActionPerformed
        // TODO add your handling code here:
      jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_parkjiminActionPerformed

    private void kimseokjinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kimseokjinActionPerformed
        // TODO add your handling code here:
       jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_kimseokjinActionPerformed

    private void junghoseokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_junghoseokActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_junghoseokActionPerformed

    private void kimnamjoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kimnamjoonActionPerformed
        // TODO add your handling code here:
       jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_kimnamjoonActionPerformed

    private void minyoongiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minyoongiActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_minyoongiActionPerformed

    private void KimtaehyungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KimtaehyungActionPerformed
        // TODO add your handling code here:
       jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_KimtaehyungActionPerformed

    private void JeonjungkookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JeonjungkookActionPerformed
        // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_JeonjungkookActionPerformed

    private void homeJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJKActionPerformed
        // TODO add your handling code here:
        rumah sm=new rumah();
        sm.setVisible(true);
    }//GEN-LAST:event_homeJKActionPerformed

    private void quitJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJKActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_quitJKActionPerformed

    private void homeSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSGActionPerformed
        // TODO add your handling code here:
        rumah sm=new rumah();
        sm.setVisible(true);
    }//GEN-LAST:event_homeSGActionPerformed

    private void quitSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitSGActionPerformed
        // TODO add your handling code here:
  dispose();
    }//GEN-LAST:event_quitSGActionPerformed

    private void homeNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeNMActionPerformed
        rumah sm=new rumah();
        sm.setVisible(true);
    }//GEN-LAST:event_homeNMActionPerformed

    private void quitNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitNMActionPerformed
       dispose();
    }//GEN-LAST:event_quitNMActionPerformed

    private void homeJHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJHActionPerformed
        // TODO add your handling code here:
        rumah sm=new rumah();
        sm.setVisible(true);
    }//GEN-LAST:event_homeJHActionPerformed

    private void quitJHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJHActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_quitJHActionPerformed

    private void homeSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSJActionPerformed
        rumah sm=new rumah();
        sm.setVisible(true);
    }//GEN-LAST:event_homeSJActionPerformed

    private void quitSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitSJActionPerformed
        dispose();
    }//GEN-LAST:event_quitSJActionPerformed

    private void homeTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeTHActionPerformed
        // TODO add your handling code here:
         rumah sm=new rumah();
        sm.setVisible(true);
    }//GEN-LAST:event_homeTHActionPerformed

    private void quitTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitTHActionPerformed
        // TODO add your handling code here:
          dispose();
    }//GEN-LAST:event_quitTHActionPerformed

    private void homeSJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSJ1ActionPerformed
        // TODO add your handling code here:
         rumah sm=new rumah();
        sm.setVisible(true);
    }//GEN-LAST:event_homeSJ1ActionPerformed

    private void quitSJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitSJ1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_quitSJ1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataMemeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataMemeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataMemeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataMemeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataMemeber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JeonJungkook;
    private javax.swing.JButton Jeonjungkook;
    private javax.swing.JPanel Junghoseok;
    private javax.swing.JPanel KimNamjoon;
    private javax.swing.JPanel KimSeokjin;
    private javax.swing.JPanel KimTaehyung;
    private javax.swing.JButton Kimtaehyung;
    private javax.swing.JPanel MinYoongi;
    private javax.swing.JPanel ParkJimin1;
    private javax.swing.JLabel background11;
    private javax.swing.JLabel background12;
    private javax.swing.JLabel background13;
    private javax.swing.JLabel background14;
    private javax.swing.JLabel background15;
    private javax.swing.JLabel background16;
    private javax.swing.JLabel background18;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel foto3;
    private javax.swing.JLabel foto4;
    private javax.swing.JLabel foto5;
    private javax.swing.JLabel foto6;
    private javax.swing.JLabel foto8;
    private javax.swing.JButton homeJH;
    private javax.swing.JButton homeJK;
    private javax.swing.JButton homeNM;
    private javax.swing.JButton homeSG;
    private javax.swing.JButton homeSJ;
    private javax.swing.JButton homeSJ1;
    private javax.swing.JButton homeTH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JButton junghoseok;
    private javax.swing.JButton kimnamjoon;
    private javax.swing.JButton kimseokjin;
    private javax.swing.JButton minyoongi;
    private javax.swing.JButton parkjimin;
    private javax.swing.JButton quitJH;
    private javax.swing.JButton quitJK;
    private javax.swing.JButton quitNM;
    private javax.swing.JButton quitSG;
    private javax.swing.JButton quitSJ;
    private javax.swing.JButton quitSJ1;
    private javax.swing.JButton quitTH;
    // End of variables declaration//GEN-END:variables
}
