/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splashscreensatu;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Splashscreensatuu extends javax.swing.JFrame {
    /**
     * Creates new form Splashscreensatuu
     */
    public Splashscreensatuu() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        TeksWELCOME = new javax.swing.JLabel();
        LoadingLabel = new javax.swing.JLabel();
        ProgresBar = new javax.swing.JProgressBar();
        LoadingValue = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setPreferredSize(new java.awt.Dimension(900, 500));
        Background.setVerifyInputWhenFocusTarget(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TeksWELCOME.setBackground(new java.awt.Color(255, 102, 0));
        TeksWELCOME.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        TeksWELCOME.setText(" WELCOME TO BTS WORLD");
        Background.add(TeksWELCOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 70));

        LoadingLabel.setText("Loading ...");
        Background.add(LoadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        Background.add(ProgresBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 650, 10));

        LoadingValue.setText("jLabel2");
        Background.add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splashscreensatu/Assets/Splash Screen.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 670, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("empty-statement")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splashscreensatuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splashscreensatuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splashscreensatuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splashscreensatuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    Splashscreensatuu sp =new Splashscreensatuu();
    sp.setVisible(true);
    
    try{
         for(int i= 0;i<=100;i++){
        Thread.sleep(25);
        sp.LoadingValue.setText( i + "%");
        if (i==10){
        sp.LoadingLabel.setText("Masih 10 %...");}
        
        if (i==20){
        sp.LoadingLabel.setText("Udah 20 %...");}
        
        if (i==50){
        sp.LoadingLabel.setText("Udah Setengah persen...");}
        
        if (i==70){
        sp.LoadingLabel.setText("Dikit lagi !...");}
        
        if (i==80){ 
        sp.LoadingLabel.setText("skuyyyyyy langsung ae!...");}
        
        sp.ProgresBar.setValue(i);
    } 
    }catch (Exception e){
   JOptionPane.showMessageDialog(null, e);
    }
    rumah masa_depan=new rumah();//Membuat Instant dari kelas Beranda
            masa_depan.setVisible(true);//Menampilkan kelas beranda
         //   this.dispose();//Menutup kelas Login
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel LoadingLabel;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JProgressBar ProgresBar;
    private javax.swing.JLabel TeksWELCOME;
    // End of variables declaration//GEN-END:variables
}
